### ISSUE TITLE
URGENT: Security hole

### ISSUE THREAD

**Issue by andrewmclagan** [WP-API/jwt-auth#28]
```php
update_user_meta( $token->data->user->id, WP_REST_Key_Pair::_USERMETA_KEY_, array_values( $keypairs ) );
```

your storing unencrypted keys in the database.... very very bad idea.

**Comment by TimothyBJacobs** [comment]
Only the hashed form of the secret is stored.

https://github.com/WP-API/jwt-auth/blob/develop/wp-includes/rest-api/auth/class-wp-rest-key-pair.php#L502
